name: tests

on:
  push:
    branches:
      - start
      - main
  pull_request:
    branches:
      - start
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          tools: composer:v2
          coverage: xdebug

      - name: SQLite
        run: touch ./database/database.sqlite

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Install Node Dependencies
        run: bun install --frozen-lockfile

      - name: Migrate
        run: php artisan migrate --force

      - name: Build Assets
        run: bun run build

      - name: Validate typescript
        run: bun run type:check

      - name: Tests
        run: php artisan test --parallel

      - name: Phpstan
        run: ./vendor/bin/phpstan analyse --memory-limit=2G --ansi
